// LOGIN USER
export const LOGIN_USER="LOGIN_USER"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";

// FETCH USERS

export const FETCH_USERS="FETCH_USERS"
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS"
export const FETCH_USERS_FAIL="FETCH_USERS_FAIL"

// FETCH CARS

export const FETCH_CARS="FETCH_CARS"
export const FETCH_CARS_SUCCESS="FETCH_CARS_SUCCESS"
export const FETCH_CARS_FAIL="FETCH_CARS_FAIL"