// LOGIN USER
export const LOGIN_USER="LOGIN_USER"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";

// FETCH USERS

export const FETCH_USERS="FETCH_USERS"
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS"
export const FETCH_USERS_FAIL="FETCH_USERS_FAIL"

// ADD USER
export const ADD_USER="ADD_USER"
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS"
export const ADD_USER_FAIL="ADD_USER_FAIL"
// FETCH CARS

export const FETCH_CARS="FETCH_CARS"
export const FETCH_CARS_SUCCESS="FETCH_CARS_SUCCESS"
export const FETCH_CARS_FAIL="FETCH_CARS_FAIL"

// DELETE USER

export const DELETE_USER="DELETE_USER"
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL="DELETE_USER_FAIL"

// EDIT USER 

export const EDIT_USER="EDIT_USER"
export const EDIT_USER_SUCCESS="EDIT_USER_SUCCESS"
export const EDIT_USER_FAIL="EDIT_USER_FAIL"

// READ USER
export const READ_USER="READ_USER"
export const READ_USER_SUCCESS="READ_USER_SUCCESS"
export const READ_USER_FAIL="READ_USER_FAIL"
// UNFETCH
export const UNFETCH_USERS="FETCH_USERS"

// MODAL VISIBLE
export const MODAL_VISIBLE="MODAL_VISIBLE"
// SLIDE MODAL VISIBLE
export const SLIDE_MODAL_VISIBLE="SLIDE_MODAL_VISIBLE";

// CLEAR
export const CLEAR_ALL_FAIL="CLEAR_ALL_FAIL"